spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 384Mi
            limits:
              cpu: "1.0"
              memory: 384Mi
