spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 2048Mi
            limits:
              cpu: "1.0"
              memory: 2048Mi
